/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author user
 */
public class TelaCaixa extends javax.swing.JPanel {

    /**
     * Creates new form Caixa
     */
    public TelaCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();

        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOTAL CAIXA:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 10, 280, 30);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(20, 50, 370, 60);

        add(jPanel1);
        jPanel1.setBounds(718, 12, 410, 140);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel2.add(jTextField2);
        jTextField2.setBounds(20, 40, 130, 40);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel2.add(jTextField3);
        jTextField3.setBounds(190, 40, 130, 40);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel2.add(jTextField4);
        jTextField4.setBounds(370, 40, 130, 40);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel2.add(jTextField5);
        jTextField5.setBounds(540, 40, 130, 40);

        jLabel2.setText("ENTRADA CARTÃO:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 116, 16);

        jLabel3.setText("ENTRADA TRANSFERENCIA:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(180, 20, 180, 16);

        jLabel4.setText("ENTRADA A PRAZO:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(540, 20, 130, 16);

        jLabel5.setText("ENTRADA DINHEIRO:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(370, 20, 140, 20);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(10, 90, 680, 10);

        add(jPanel2);
        jPanel2.setBounds(10, 10, 700, 630);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);
        add(jPanel3);
        jPanel3.setBounds(720, 160, 410, 480);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
