/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controle.Fornecedor;
import controle.Produto;
import conexao.NewHibernateUtil;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author user
 */
public class TelaProdutoFornecedor extends javax.swing.JPanel {

    Fornecedor fornecedor;

    public Fornecedor getFornecedor() {
        return fornecedor;
    }

    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

    public TelaProdutoFornecedor() {
        initComponents();

        // modifica a largura das colunas da tabela.
        TableColumn colCodigo = table_Product.getColumnModel().getColumn(0);
        TableColumn colNome = table_Product.getColumnModel().getColumn(1);
        TableColumn colQuantidade = table_Product.getColumnModel().getColumn(2);
        TableColumn colPreço = table_Product.getColumnModel().getColumn(3);

        colCodigo.setPreferredWidth(5);
        colNome.setPreferredWidth(350);
        colQuantidade.setPreferredWidth(5);
        colPreço.setPreferredWidth(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Product = new javax.swing.JTable();

        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUTOS DO FORNECEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jPanel1.setLayout(null);

        table_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Qtde:", "Preço:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_Product);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 800, 290);

        add(jPanel1);
        jPanel1.setBounds(10, 290, 1120, 350);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Product;
    // End of variables declaration//GEN-END:variables

    public void produtosFornecedor() {

        Session session = NewHibernateUtil.getSessionFactory().openSession();
        Transaction tx = session.beginTransaction();
        
        // juntando duas tabelas do banco de dados;
        String sql = "FROM Produto as v INNER JOIN v.fornecedor";
        List<Object[]> query = (List<Object[]>) session.createQuery(sql).list();
        DefaultTableModel tabela = (DefaultTableModel) table_Product.getModel();
        tabela.setNumRows(0);
        for (Object[] objects : query) {
            Produto produto = (Produto) objects[0];
            Fornecedor forne = (Fornecedor) objects[1];
            if (forne.getIdFornecedor().equals(fornecedor.getIdFornecedor())) {
                System.out.println(fornecedor.getNome() + "----" + produto.getNome());       
                tabela.addRow(new Object[]{produto.getIdProduto(), produto.getNome(), produto.getQnt(), produto.getValor_venda()});
            }

        }
    }

}
