package com.systema.projetows;
// Generated 28/09/2020 12:30:31 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente",
         catalog = "SistemaVendas"
)
public class Cliente implements java.io.Serializable {

    private Integer idcliente;
    private Date clienteDesde;
    private Long limiteCredito;
    private List<Venda> vendas;
    private List<Pessoa> pessoas;

    public Cliente() {
    }

    public Cliente(Date clienteDesde, Long limiteCredito, List<Venda> vendas, List<Pessoa> pessoas) {
        this.clienteDesde = clienteDesde;
        this.limiteCredito = limiteCredito;
        this.vendas = vendas;
        this.pessoas = pessoas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idcliente", unique = true, nullable = false)
    public Integer getIdcliente() {
        return this.idcliente;
    }

    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "cliente_desde", length = 10)
    public Date getClienteDesde() {
        return this.clienteDesde;
    }

    public void setClienteDesde(Date clienteDesde) {
        this.clienteDesde = clienteDesde;
    }

    @Column(name = "limite_credito", precision = 10, scale = 0)
    public Long getLimiteCredito() {
        return this.limiteCredito;
    }

    public void setLimiteCredito(Long limiteCredito) {
        this.limiteCredito = limiteCredito;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
    public List<Venda> getVendas() {
        return this.vendas;
    }

    public void setVendas(List<Venda> vendas) {
        this.vendas = vendas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
    public List<Pessoa> getPessoas() {
        return this.pessoas;
    }

    public void setPessoas(List<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }

}
