package com.systema.projetows;
// Generated 28/09/2020 12:30:31 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa",
        catalog = "SistemaVendas"
)
public class Pessoa implements java.io.Serializable {

    private int idpessoa;
    private Endereco endereco;
    private Cliente cliente;
    private Usuario usuario;
    private String nome;
    private Long cpf;
    private String email;
    private boolean status;
    private Date dataNascimento;
    private List<NumeroContato> numeroContatos;

    public Pessoa() {
    }

    public Pessoa(Endereco endereco, Cliente cliente, Usuario usuario, String nome, Long cpf, String email, boolean status, Date dataNascimento, List<NumeroContato> numeroContatos) {
        this.endereco = endereco;
        this.cliente = cliente;
        this.usuario = usuario;
        this.nome = nome;
        this.cpf = cpf;
        this.email = email;
        this.status = status;
        this.dataNascimento = dataNascimento;
        this.numeroContatos = numeroContatos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idpessoa", unique = true, nullable = false)
    public int getIdpessoa() {
        return this.idpessoa;
    }

    public void setIdpessoa(int idpessoa) {
        this.idpessoa = idpessoa;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "endereco_id")
    public Endereco getEndereco() {
        return this.endereco;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cliente_id")
    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario_id")
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "nome", length = 65)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "cpf")
    public Long getCpf() {
        return this.cpf;
    }

    public void setCpf(Long cpf) {
        this.cpf = cpf;
    }

    @Column(name = "email", length = 45)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "numero_contato")
    public boolean isStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_nascimento", length = 10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }

    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
    public List<NumeroContato> getNumeroContatos() {
        return this.numeroContatos;
    }

    public void setNumeroContatos(List<NumeroContato> numeroContatos) {
        this.numeroContatos = numeroContatos;
    }

//    METODOS ESPECIFICOS DA CLASSE
    public NumeroContato Contato(List<NumeroContato> contato) {
        for (NumeroContato numero : contato) {
            if (this.idpessoa == numero.getPessoa().getIdpessoa()) {
                return numero;
            }
        }
        return null;
    }

    public List<NumeroContato> FiltrodeContatos(List<NumeroContato> numeros) {

        for (NumeroContato numero : numeros) {
            if (this.idpessoa == numero.getPessoa().getIdpessoa()) {
                this.numeroContatos.add(numero);
            }
        }

        return this.numeroContatos;
    }

}
