/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.system.telas;

import com.system.conexao.Conexao;
import com.system.sistemamaven.Items;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author willian
 */
public class Pesquisas extends javax.swing.JFrame {

    Conexao banco = new Conexao();
    TelaEdicao tela = new TelaEdicao();

    /**
     * Creates new form Pesquisas
     */
    public Pesquisas() {
        initComponents();
        btn_editar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTable = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_items2 = new javax.swing.JTable();
        camp_pesquisa2 = new javax.swing.JTextField();
        btn_pesquisa2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_items1 = new javax.swing.JTable();
        camp_pesquisa1 = new javax.swing.JTextField();
        btn_pesquisa1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        camp_pesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_items = new javax.swing.JTable();
        btn_editar = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        checkBox_valor = new javax.swing.JCheckBox();
        checkBox_tamanho = new javax.swing.JCheckBox();
        checkBox_qnt = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuIDesativarItens = new javax.swing.JMenuItem();
        jMenuExcluirItens = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_items2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "nome", "cnpj", "email", "home page", "rua", "cep", "bairro", "contato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_items2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 820, 220));
        jPanel1.add(camp_pesquisa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 370, 30));

        btn_pesquisa2.setText("pesquisar");
        btn_pesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pesquisa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 100, 30));

        jLabel3.setText("Pesquisa:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, -1));

        jPanelTable.addTab("Fornecedor", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_items1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "nome", "cpf", "email", "contato", "data nascimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_items1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 820, 220));
        jPanel2.add(camp_pesquisa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 370, 30));

        btn_pesquisa1.setText("pesquisar");
        btn_pesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisa1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_pesquisa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 110, 30));

        jLabel2.setText("Pesquisa:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, -1));

        jPanelTable.addTab("Pessoas", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(camp_pesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 370, 30));

        jLabel1.setText("Pesquisa:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, -1));

        table_items.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "codigo", "nome", "valor", "qnt", "fornecedor", "descrição", "tamanho", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_itemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_items);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 820, 190));

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 90, 40));

        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 820, 10));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 820, 10));

        jInternalFrame1.setTitle("Filtrar por:");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkBox_valor.setText("Valor:");
        checkBox_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_valorActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(checkBox_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 160, -1));

        checkBox_tamanho.setText(" Tamanho:");
        checkBox_tamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_tamanhoActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(checkBox_tamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        checkBox_qnt.setText("Quantidade:");
        checkBox_qnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_qntActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(checkBox_qnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 170, -1));

        jPanel3.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 300, 110));

        jPanelTable.addTab("Itens", jPanel3);

        getContentPane().add(jPanelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 900, 470));

        jMenu1.setText("Opções");

        jMenuIDesativarItens.setText("Desativar itens");
        jMenuIDesativarItens.setEnabled(false);
        jMenuIDesativarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIDesativarItensActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIDesativarItens);

        jMenuExcluirItens.setText("Excluir itens");
        jMenuExcluirItens.setEnabled(false);
        jMenu1.add(jMenuExcluirItens);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(965, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        EditarItem();
        tela.setVisible(true);
        tela.CarregarCampos();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_pesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pesquisa1ActionPerformed

    private void btn_pesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pesquisa2ActionPerformed

    private void table_itemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_itemsMouseClicked
        btn_editar.setVisible(true);
    }//GEN-LAST:event_table_itemsMouseClicked

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        AtualizarTabela();
        btn_editar.setVisible(false);
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void jMenuIDesativarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIDesativarItensActionPerformed
        DesativarItens();
    }//GEN-LAST:event_jMenuIDesativarItensActionPerformed

    private void checkBox_tamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_tamanhoActionPerformed
        if (checkBox_tamanho.isSelected()) {
            checkBox_qnt.setEnabled(false);
            checkBox_valor.setEnabled(false);
        } else {
            checkBox_qnt.setEnabled(true);
            checkBox_valor.setEnabled(true);
        }

    }//GEN-LAST:event_checkBox_tamanhoActionPerformed

    private void checkBox_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_valorActionPerformed
        if (checkBox_valor.isSelected()) {
            checkBox_tamanho.setEnabled(false);
            checkBox_qnt.setEnabled(false);
        } else {
            checkBox_qnt.setEnabled(true);
            checkBox_tamanho.setEnabled(true);
        }
    }//GEN-LAST:event_checkBox_valorActionPerformed

    private void checkBox_qntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_qntActionPerformed
        if (checkBox_qnt.isSelected()) {
            checkBox_tamanho.setEnabled(false);
            checkBox_valor.setEnabled(false);
        } else {
            checkBox_tamanho.setEnabled(true);
            checkBox_valor.setEnabled(true);
        }
    }//GEN-LAST:event_checkBox_qntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_pesquisa1;
    private javax.swing.JButton btn_pesquisa2;
    private javax.swing.JTextField camp_pesquisa;
    private javax.swing.JTextField camp_pesquisa1;
    private javax.swing.JTextField camp_pesquisa2;
    private javax.swing.JCheckBox checkBox_qnt;
    private javax.swing.JCheckBox checkBox_tamanho;
    private javax.swing.JCheckBox checkBox_valor;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuExcluirItens;
    public javax.swing.JMenuItem jMenuIDesativarItens;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jPanelTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable table_items;
    private javax.swing.JTable table_items1;
    private javax.swing.JTable table_items2;
    // End of variables declaration//GEN-END:variables

    public void AtualizarTabela() {

        String pesquisa = camp_pesquisa.getText();
        
        List<Items> items = new ArrayList<>();

        if (!checkBox_valor.isSelected() && !checkBox_tamanho.isSelected() && !checkBox_qnt.isSelected()) {
            for (int i = 0; i < banco.list_Items().size(); i++) {
                if (banco.list_Items().get(i).getItem().contains(pesquisa)) {   // VERIFICA SE O TAMANHO CONTEM NO BANCO DE DADOS
                    Items item = banco.list_Items().get(i);
                    if (item.isStatus()) {                                    // ESSE IF VAI ADICIONAR NA ARRAYLIST APENAS OS ITEMS QUE TIVEREM COM STATUS TRUE
                        items.add(item);                                     // ADICIONA O ITEM DA PESQUISA NA ARRAYLIST
                    }
                }
            }
        }

        if (checkBox_tamanho.isSelected() == true) {
            for (int i = 0; i < banco.list_Items().size(); i++) {
                if (banco.list_Items().get(i).getTamanho().contains(pesquisa)) {   // VERIFICA SE O TAMANHO CONTEM NO BANCO DE DADOS
                    Items item = banco.list_Items().get(i);
                    if (item.isStatus()) {                                    // ESSE IF VAI ADICIONAR NA ARRAYLIST APENAS OS ITEMS QUE TIVEREM COM STATUS TRUE
                        items.add(item);                                     // ADICIONA O ITEM DA PESQUISA NA ARRAYLIST
                    }
                }
            }
        }
        if (checkBox_valor.isSelected() == true) {
            Long valor = Long.parseLong(pesquisa) * 100;
            for (int i = 0; i < banco.list_Items().size(); i++) {
                if (banco.list_Items().get(i).getValor_venda().longValue() == valor) {   // VERIFICA SE O VALOR CONTEM NO BANCO DE DADOS
                    Items item = banco.list_Items().get(i);
                    if (item.isStatus()) {                                    // ESSE IF VAI ADICIONAR NA ARRAYLIST APENAS OS ITEMS QUE TIVEREM COM STATUS TRUE
                        items.add(item);                                     // ADICIONA O ITEM DA PESQUISA NA ARRAYLIST
                    }
                }
            }
        }
        if (checkBox_qnt.isSelected() == true) {
            Long valor = Long.parseLong(pesquisa);
            for (int i = 0; i < banco.list_Items().size(); i++) {
                if (banco.list_Items().get(i).getQnt().intValue() == valor) {   // VERIFICA SE A QNT CONTEM NO BANCO DE DADOS
                    Items item = banco.list_Items().get(i);
                    if (item.isStatus()) {                                    // ESSE IF VAI ADICIONAR NA ARRAYLIST APENAS OS ITEMS QUE TIVEREM COM STATUS TRUE
                        items.add(item);                                     // ADICIONA O ITEM DA PESQUISA NA ARRAYLIST
                    }
                }
            }
        }

        DefaultTableModel tableDefault = (DefaultTableModel) table_items.getModel();
        try {

            tableDefault.setNumRows(0); // LIMPA OS NOMES DA PESQUISA ENTERIOR
            for (Items item : items) {
                float l = item.getValor_venda() / 100; // A DIVISÃO POR 100 É APENAS PRA MOVER A VIRGULA 3 CASAS DECIMAIS.
                float t = item.getValor_total() / 100; // A DIVISÃO POR 100 É APENAS PRA MOVER A VIRGULA 3 CASAS DECIMAIS.

                String valorVenda = Float.toString(l);
                String valorTotal = Float.toString(t);

                tableDefault.addRow(new Object[]{item.getIditem(), item.getCodigo(), item.getItem(), "R$ " + valorVenda,
                    item.getQnt(), item.getFornecedor(), item.getDescricao(), item.getTamanho(), "R$ " + valorTotal});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "<Item não Encontrado>");
        }

    }

    private void EditarItem() {

        DefaultTableModel tableDefault = (DefaultTableModel) table_items.getModel();
        int linha = table_items.getSelectedRow();

        for (int i = 0; i < banco.list_Items().size(); i++) {
            if (banco.list_Items().get(i).getIditem().equals(tableDefault.getValueAt(linha, 0))) { // VERIFICA SE O ID DO OBJETO ONTEM NO BANCO DE DADOS
                Items item = banco.list_Items().get(i);
                tela.setItem(item); //MANDA O ITEM SELECIONADO PARA OUTRA TELA UTILIZANDO O METODO GETT E SETT
            }
        }
    }

    private void DesativarItens() {

        int confirmacao = JOptionPane.showConfirmDialog(null, "Você Deseja desativar *OS ITENS SELECIONADOS*?", "Desativar", JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION) {

            DefaultTableModel tableDefault = (DefaultTableModel) table_items.getModel();
            int linha = table_items.getSelectedRow();

            for (int i = 0; i < banco.list_Items().size(); i++) {
                if (banco.list_Items().get(i).getIditem().equals(tableDefault.getValueAt(linha, 0))) { // VERIFICA SE O ID DO OBJETO CONTEM NO BANCO DE DADOS
                    Items item = banco.list_Items().get(i);
                    item.setStatus(false);
                    banco.update(item);
                    AtualizarTabela();
                }
            }
            JOptionPane.showMessageDialog(null, "Item *DESATIVADOS* com Sucesso!");
            JOptionPane.showMessageDialog(null, "Voce pode ativa-los novamente quando quiser, basta ir na\ntela principal do sistema na barra menu configurações!");

        }
    }
}
