package Classes;
// Generated 27/09/2020 16:30:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private Date clienteDesde;
     private Long limiteCredito;
     private Set vendas = new HashSet(0);
     private Set pessoas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(Date clienteDesde, Long limiteCredito, Set vendas, Set pessoas) {
       this.clienteDesde = clienteDesde;
       this.limiteCredito = limiteCredito;
       this.vendas = vendas;
       this.pessoas = pessoas;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public Date getClienteDesde() {
        return this.clienteDesde;
    }
    
    public void setClienteDesde(Date clienteDesde) {
        this.clienteDesde = clienteDesde;
    }
    public Long getLimiteCredito() {
        return this.limiteCredito;
    }
    
    public void setLimiteCredito(Long limiteCredito) {
        this.limiteCredito = limiteCredito;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }




}


