package Classes;
// Generated 27/09/2020 16:30:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private Integer idEndereco;
     private String rua;
     private Integer cep;
     private String bairro;
     private Integer numeroCasa;
     private String complemento;
     private String estadoUf;
     private String cidade;
     private Set pessoas = new HashSet(0);

    public Endereco() {
    }

    public Endereco(String rua, Integer cep, String bairro, Integer numeroCasa, String complemento, String estadoUf, String cidade, Set pessoas) {
       this.rua = rua;
       this.cep = cep;
       this.bairro = bairro;
       this.numeroCasa = numeroCasa;
       this.complemento = complemento;
       this.estadoUf = estadoUf;
       this.cidade = cidade;
       this.pessoas = pessoas;
    }
   
    public Integer getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(Integer idEndereco) {
        this.idEndereco = idEndereco;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public Integer getCep() {
        return this.cep;
    }
    
    public void setCep(Integer cep) {
        this.cep = cep;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public Integer getNumeroCasa() {
        return this.numeroCasa;
    }
    
    public void setNumeroCasa(Integer numeroCasa) {
        this.numeroCasa = numeroCasa;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getEstadoUf() {
        return this.estadoUf;
    }
    
    public void setEstadoUf(String estadoUf) {
        this.estadoUf = estadoUf;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }




}


