package Classes;
// Generated 27/09/2020 16:30:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPagamento generated by hbm2java
 */
public class FormaPagamento  implements java.io.Serializable {


     private Integer idformaPagamento;
     private String cartaoDebito;
     private String dinheiroAVista;
     private String parcelado1x;
     private String parcelado3x;
     private String parcelado5x;
     private String parcelado10x;
     private Set vendas = new HashSet(0);

    public FormaPagamento() {
    }

    public FormaPagamento(String cartaoDebito, String dinheiroAVista, String parcelado1x, String parcelado3x, String parcelado5x, String parcelado10x, Set vendas) {
       this.cartaoDebito = cartaoDebito;
       this.dinheiroAVista = dinheiroAVista;
       this.parcelado1x = parcelado1x;
       this.parcelado3x = parcelado3x;
       this.parcelado5x = parcelado5x;
       this.parcelado10x = parcelado10x;
       this.vendas = vendas;
    }
   
    public Integer getIdformaPagamento() {
        return this.idformaPagamento;
    }
    
    public void setIdformaPagamento(Integer idformaPagamento) {
        this.idformaPagamento = idformaPagamento;
    }
    public String getCartaoDebito() {
        return this.cartaoDebito;
    }
    
    public void setCartaoDebito(String cartaoDebito) {
        this.cartaoDebito = cartaoDebito;
    }
    public String getDinheiroAVista() {
        return this.dinheiroAVista;
    }
    
    public void setDinheiroAVista(String dinheiroAVista) {
        this.dinheiroAVista = dinheiroAVista;
    }
    public String getParcelado1x() {
        return this.parcelado1x;
    }
    
    public void setParcelado1x(String parcelado1x) {
        this.parcelado1x = parcelado1x;
    }
    public String getParcelado3x() {
        return this.parcelado3x;
    }
    
    public void setParcelado3x(String parcelado3x) {
        this.parcelado3x = parcelado3x;
    }
    public String getParcelado5x() {
        return this.parcelado5x;
    }
    
    public void setParcelado5x(String parcelado5x) {
        this.parcelado5x = parcelado5x;
    }
    public String getParcelado10x() {
        return this.parcelado10x;
    }
    
    public void setParcelado10x(String parcelado10x) {
        this.parcelado10x = parcelado10x;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


