package Classes;
// Generated 27/09/2020 16:30:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Items generated by hbm2java
 */
public class Items  implements java.io.Serializable {


     private Integer iditem;
     private String item;
     private Long valor;
     private boolean status;
     private Long peso;
     private int codigo;
     private Integer qnt;
     private String descricao;
     private Set itensVendas = new HashSet(0);

    public Items() {
    }

	
    public Items(boolean status, int codigo) {
        this.status = status;
        this.codigo = codigo;
    }
    public Items(String item, Long valor, boolean status, Long peso, int codigo, Integer qnt, String descricao, Set itensVendas) {
       this.item = item;
       this.valor = valor;
       this.status = status;
       this.peso = peso;
       this.codigo = codigo;
       this.qnt = qnt;
       this.descricao = descricao;
       this.itensVendas = itensVendas;
    }
   
    public Integer getIditem() {
        return this.iditem;
    }
    
    public void setIditem(Integer iditem) {
        this.iditem = iditem;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public Long getValor() {
        return this.valor;
    }
    
    public void setValor(Long valor) {
        this.valor = valor;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Long getPeso() {
        return this.peso;
    }
    
    public void setPeso(Long peso) {
        this.peso = peso;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Integer getQnt() {
        return this.qnt;
    }
    
    public void setQnt(Integer qnt) {
        this.qnt = qnt;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getItensVendas() {
        return this.itensVendas;
    }
    
    public void setItensVendas(Set itensVendas) {
        this.itensVendas = itensVendas;
    }




}


