package Classes;
// Generated 27/09/2020 16:30:38 by Hibernate Tools 4.3.1



/**
 * ItensVenda generated by hbm2java
 */
public class ItensVenda  implements java.io.Serializable {


     private Integer iditensVenda;
     private Items items;
     private Venda venda;
     private Integer qnt;
     private Boolean status;

    public ItensVenda() {
    }

    public ItensVenda(Items items, Venda venda, Integer qnt, Boolean status) {
       this.items = items;
       this.venda = venda;
       this.qnt = qnt;
       this.status = status;
    }
   
    public Integer getIditensVenda() {
        return this.iditensVenda;
    }
    
    public void setIditensVenda(Integer iditensVenda) {
        this.iditensVenda = iditensVenda;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
    public Integer getQnt() {
        return this.qnt;
    }
    
    public void setQnt(Integer qnt) {
        this.qnt = qnt;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


