package Classes;
// Generated 27/09/2020 16:30:38 by Hibernate Tools 4.3.1



/**
 * NumeroContato generated by hbm2java
 */
public class NumeroContato  implements java.io.Serializable {

     private Integer idNumeroContato;
     private Pessoa pessoa;
     private Integer ddd;
     private Integer fone;
     private Integer cpf;

    public NumeroContato() {
    }

    public NumeroContato(Pessoa pessoa, Integer ddd, Integer fone, Integer cpf) {
       this.pessoa = pessoa;
       this.ddd = ddd;
       this.fone = fone;
       this.cpf = cpf;
    }
   
    public Integer getIdNumeroContato() {
        return this.idNumeroContato;
    }
    
    public void setIdNumeroContato(Integer idNumeroContato) {
        this.idNumeroContato = idNumeroContato;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Integer getDdd() {
        return this.ddd;
    }
    
    public void setDdd(Integer ddd) {
        this.ddd = ddd;
    }
    public Integer getFone() {
        return this.fone;
    }
    
    public void setFone(Integer fone) {
        this.fone = fone;
    }
    public Integer getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Integer cpf) {
        this.cpf = cpf;
    }




}


