package Classes;
// Generated 27/09/2020 16:30:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer idpessoa;
     private Endereco endereco;
     private Cliente cliente;
     private Usuario usuario;
     private String nome;
     private Integer cpf;
     private String email;
     private Integer numeroContato;
     private Date dataNascimento;
     private Set numeroContatos = new HashSet(0);

    public Pessoa() {
    }

    public Pessoa(Endereco endereco, Cliente cliente, Usuario usuario, String nome, Integer cpf, String email, Integer numeroContato, Date dataNascimento, Set numeroContatos) {
       this.endereco = endereco;
       this.cliente = cliente;
       this.usuario = usuario;
       this.nome = nome;
       this.cpf = cpf;
       this.email = email;
       this.numeroContato = numeroContato;
       this.dataNascimento = dataNascimento;
       this.numeroContatos = numeroContatos;
    }
   
    public Integer getIdpessoa() {
        return this.idpessoa;
    }
    
    public void setIdpessoa(Integer idpessoa) {
        this.idpessoa = idpessoa;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Integer cpf) {
        this.cpf = cpf;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getNumeroContato() {
        return this.numeroContato;
    }
    
    public void setNumeroContato(Integer numeroContato) {
        this.numeroContato = numeroContato;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public Set getNumeroContatos() {
        return this.numeroContatos;
    }
    
    public void setNumeroContatos(Set numeroContatos) {
        this.numeroContatos = numeroContatos;
    }




}


