package com.system.sistemamaven;
// Generated 28/09/2020 12:30:31 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NumeroContato generated by hbm2java
 */
@Entity
@Table(name="Numero_contato"
    ,catalog="bancoSistemaVenda"
)
public class NumeroContato  implements java.io.Serializable {


     private Integer idNumeroContato;
     private Fornecedor fornecedor;
     private Pessoa pessoa;
     private Integer ddd;
     private Integer fone;
     private Integer cpf;

    public NumeroContato() {
    }

    public NumeroContato(Fornecedor fornecedor, Pessoa pessoa, Integer ddd, Integer fone, Integer cpf) {
       this.fornecedor = fornecedor;
       this.pessoa = pessoa;
       this.ddd = ddd;
       this.fone = fone;
       this.cpf = cpf;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idNumero_contato", unique=true, nullable=false)
    public Integer getIdNumeroContato() {
        return this.idNumeroContato;
    }
    
    public void setIdNumeroContato(Integer idNumeroContato) {
        this.idNumeroContato = idNumeroContato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fornecedor_id")
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa_id")
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="ddd")
    public Integer getDdd() {
        return this.ddd;
    }
    
    public void setDdd(Integer ddd) {
        this.ddd = ddd;
    }

    
    @Column(name="fone")
    public Integer getFone() {
        return this.fone;
    }
    
    public void setFone(Integer fone) {
        this.fone = fone;
    }

    
    @Column(name="cpf")
    public Integer getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Integer cpf) {
        this.cpf = cpf;
    }




}


