/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.systema.telas;

import java.awt.Color;

/**
 *
 * @author willian
 */
public class MainScreen extends javax.swing.JFrame {

    Color standardColor;

    public MainScreen() {
        initComponents();
        standardColor = new Color(170, 255, 160);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuLateral = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(170, 255, 160));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 50);

        menuLateral.setBackground(new java.awt.Color(170, 255, 160));
        menuLateral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuLateral.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(170, 255, 160));
        jPanel5.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel1");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FocoMouse(evt);
            }
        });
        jPanel5.add(jLabel4);
        jLabel4.setBounds(0, 0, 220, 60);

        menuLateral.add(jPanel5);
        jPanel5.setBounds(0, 350, 220, 60);

        jPanel4.setBackground(new java.awt.Color(170, 255, 160));
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel1");
        jLabel3.setToolTipText("");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FocoMouse(evt);
            }
        });
        jPanel4.add(jLabel3);
        jLabel3.setBounds(0, 0, 220, 60);

        menuLateral.add(jPanel4);
        jPanel4.setBounds(0, 280, 220, 60);

        jPanel3.setBackground(new java.awt.Color(170, 255, 160));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel1");
        jLabel2.setToolTipText("");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FocoMouse(evt);
            }
        });
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 220, 60);

        menuLateral.add(jPanel3);
        jPanel3.setBounds(0, 210, 220, 60);

        jPanel2.setBackground(new java.awt.Color(170, 255, 160));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FocoMouse(evt);
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 220, 60);

        menuLateral.add(jPanel2);
        jPanel2.setBounds(0, 140, 220, 60);
        menuLateral.add(jSeparator1);
        jSeparator1.setBounds(10, 410, 200, 20);
        menuLateral.add(jSeparator2);
        jSeparator2.setBounds(10, 200, 200, 20);
        menuLateral.add(jSeparator3);
        jSeparator3.setBounds(10, 270, 200, 20);
        menuLateral.add(jSeparator4);
        jSeparator4.setBounds(10, 340, 200, 20);

        getContentPane().add(menuLateral);
        menuLateral.setBounds(0, 50, 220, 650);

        jDesktopPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FocoMouse(evt);
            }
        });
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(220, 50, 1140, 650);

        setSize(new java.awt.Dimension(1370, 732));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FocoMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FocoMouse
        if (evt.getSource() == jLabel1) {
            jPanel2.setBackground(Color.white);
        } else {
            jPanel2.setBackground(standardColor);
        }
        if (evt.getSource() == jLabel2) {
            jPanel3.setBackground(Color.white);
        } else {
            jPanel3.setBackground(standardColor);
        }
        if (evt.getSource() == jLabel3) {
            jPanel4.setBackground(Color.white);
        } else {
            jPanel4.setBackground(standardColor);
        }
        if (evt.getSource() == jLabel4) {
            jPanel5.setBackground(Color.white);
        } else {
            jPanel5.setBackground(standardColor);
        }
    }//GEN-LAST:event_FocoMouse

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel menuLateral;
    // End of variables declaration//GEN-END:variables
}
